### ISSUE TITLE
1.2.1 Introduction

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#37]
### Issue Description 
1. Task ID: 05
2. Task: Fill up the introduction of M1 Report
      
      - [x] #38 
      - [x] #39 
      - [x] #40 
      - [x] #41 
      
3. Goals: Introduction & sub-issues completed
4. Completion Criteria: All of 1.2.1 completed and vetted
5. Allocated Time: 8/30/2023 - 9/1/2023
6. Owner: Cheryl, Elizabeth, Jia Jin, Jin Yuan
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- Introduction written but not vetted yet
- Document has been shared to team's google drive
- This heavily affects the project as it is a submission requirement
- Changes will be made as it is still in progress
- 9/12/2023 - 9/16/2023

**Comment by cheryl-tc** [comment]
### Issue Comment
- Introduction along with sub-tasks #38, #39, #40, #41 has been completed
- All required information have been inputted inside the M1 report which is inside the team's google drive
- This heavily affects the project timeline due to all these tasks being part of the submission requirement
- No more changes will be made for all these tasks as they have been completed and vetted by the team
- 9/19/2023 - 9/19/2023. A delay for these tasks due to the workload caused by the other modules which affected the team in their work management
