### ISSUE TITLE
1.2.1.2 Related Background Literature

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#39]
### Issue Description 
1. Task ID: 07
2. Task: Related Background Literature for M1 Report
3. Goals: To do research on HRMS and related information for project
4. Completion Criteria: All research done and written in M1 report
5. Allocated Time: 8/30/2023 - 9/1/2023
6. Owner: Jia Jin
7. Priority: Medium

**Comment by UncleHengz** [comment]
### Issue Comment
- Background research is still in progress
- Research written in M1 report which is inside team's google drive
- This heavily affects the project as it is a submission requirement
- Changes will be made as additional research is required
- 8/30/2023 - 9/12/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Background research has been completed. This was behind time due to other modules increasing the team's workload.
- Relevant workload management systems used by various music schools and other Human Resource Managment Systems have been researched and inputted into the M1 Report document inside the team's google drive folder
- This heavily affects the project as it is a submission requirement for the M1 Report
- No more changes will be made as all member has vetted the background research and have agreed with them
- 9/16/2023 - 9/18/2023
