### ISSUE TITLE
1.2.1.3 Intended Audience & Document Overview

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#40]
### Issue Description 
1. Task ID: 08
2. Task: Intended Audience & Document Overview of M1 Report
3. Goals: Complete Intended Audience & Document Overview
4. Completion Criteria: Intended Audience & Document Overview filled up and vetted
5. Allocated Time: 8/30/2023 - 8/31/2023
6. Owner: Jin Yuan
7. Priority: Low

**Comment by UncleHengz** [comment]
### Issue Comment
- Intended Audience & Document Overview not started yet
- Nothing has been filled in the M1 report for Intended Audience & Document Overview
- This slightly affects the project timeline as it is part of the submission requirement
- Changes will be made once this is in progress or completed
- 16/9/2023 - 16/9/2023

**Comment by jinyuan98** [comment]
### Issue Comment
- Intended Audience & Document Overview have been completed. Stakeholders of the project along with the overview of the document has been completed
- The above has been filled in inside the M1 report which is inside the team's google drive
- This slightly affects the project timeline as not only is it part of the submission, it also lays out the focus audience of the project so that the team does not go off topic
- No more changes will be made as this has been completed and vetted by the team
- 17/9/2023 - 17/9/2023. There was a delay in this as this was actually written earlier but the team had yet to vet what was written. Also, the team has been slightly overloaded with the other modules' workload
