### ISSUE TITLE
1.2.1.4 References & Acknowledgements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#41]
### Issue Description 
1. Task ID: 09
2. Task: References & Acknowledgements of M1 Report
3. Goals: References & Acknowledgements to be filled in when doing #39 
4. Completion Criteria: References & Acknowledgements done up properly in good formatting inside M1 report
5. Allocated Time: 8/30/2023 - 8/30/2023
6. Owner: Cheryl
7. Priority: Medium

**Comment by UncleHengz** [comment]
### Issue Comment
- References & Acknowledgements not started yet
- Will be filled when doing #39 
- This moderately affects the project due to it being part of the M1 submission requirement
- Changes will be made when doing #39 
- 9/16/2023 - 9/16/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- References & Acknowledgements has been completed as #39 has been completed
- All references & acknowledgements have been completed and has been entered inside the M1 report following IEEE Reference format
- This moderately affects the project due the information written could be considered plagiarism without proper citation and referencing
- No more changes will be made as the task is completed and other critical tasks has to be completed
- 9/19/2023 - 9/19/2023. There is a delay to this task as due to other modules, the workload of the team has increased
