### ISSUE TITLE
1.2.2 Overall Description

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#42]
### Issue Description 
1. Task ID: 10
2. Task: Overall Description of M1 Report

      - [x] #43 
      - [x] #44 
      - [x] #45 

3. Goals: Overall Description & Sub-Issues to be done
4. Completion Criteria: All of 1.2.2 completed and vetted
5. Allocated Time: 9/1/2023 - 9/4/2023
6. Owner: Cheryl, Jia Jin, Jin Yuan
7. Priority: Medium

**Comment by UncleHengz** [comment]
### Issue Comment
- Overall Description not done yet
- Nothing has been filled in the M1 report
- This moderately affects the project timeline as it is part of the M1 submission
- Changes will be made once progress has been made
- 9/16/2023 - 9/16/2023

**Comment by cheryl-tc** [comment]
### Issue Comment
- Overall Description has been completed. Tasks #43, #44, #45 has been completed
- All mentioned tasks have been completed and inputted inside M1 report inside the team's google drive
- This moderately affects the project timeline as all of these are part of the M1 submission criteria
- No more changes will be made as all tasks have been completed
- 9/20/2023 - 9/20/2023. There was a delay in the tasks due to the other modules' workload
