### ISSUE TITLE
1.2.2.1 Product Overview

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#43]
### Issue Description 
1. Task ID: 11
2. Task: Product Overview of M1 Report
3. Goals: To have this completed during allocated time
4. Completion Criteria: 1 paragraph and System Architecture to be done and inserted into M1 report
5. Allocated Time: 9/1/2023 - 9/2/2023
6. Owner: Cheryl
7. Priority: Medium

**Comment by UncleHengz** [comment]
### Issue Comment
- Task has not been started yet
- Nothing has been filled for this portion in M1 report
- This moderately affects the project timeline due to it being part of the M1 submission
- Changes will be made when this is in progress
- 9/16/2023 - 9/16/2023

**Comment by cheryl-tc** [comment]
### Issue Comment
- Product overview completed. A simple system architecture along with explanation has been done
- All the above has been inputted into the M1 report inside the team's google drive
- The moderately affects the project timeline due to it is required give an overview of the product and is part of the M1 report
- No more changes will be made
- 9/17/2023 - 9/20/2023. There is delay to the task as there were other modules' workload that the team has to handle
