### ISSUE TITLE
1.2.3.1 User Interface Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#47]
### Issue Description
1. Task ID: 15
2. Task: To lay out the functional requirements of the project
3. Goals: All functional requirements of the project are laid out
4. Completion Criteria: All user interface requirements of the project are established
5. Allocated Time: 8/30/2023 - 9/18/2023
6. Owner: Elizabeth
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- An Activity Flow Diagram has been created
- Have not been placed inside the M1 report
- This heavily affects the timeline as it is a requirement of the project
- Changes may be made, once done, it would be placed inside the report
- 9/14/2023 - 9/16/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Activity Flow diagram still in progress
- It is inside the team's google drive but not inside the M1 report
- This heavily affects the timeline as it illustrates the flow of the product
- Changes will still be made as there are edits to it. There is a delay too as the team is unsure of how the activity flow diagram should look like at the requirement specification stage
- 9/19/2023 - 9/20/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Activity Flow diagram is completed and requirements are laid out
- All required information has been inserted into the M1 report
- This heavily affects the project dateline as it lays out the user interface requirements and the diagram illustrates the flow. A delay to finish this task is due to the team is unsure whether certain requirements should be under user interface or non-functional requirements.
- No more changes will be made
- 9/22/2023 - 9/22/2023
