### ISSUE TITLE
1.2.3.4.1 Performance Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#51]
### Issue Description
1. Task Title: 19
2. Task: To lay out the performance requirements of the project
3. Goals: Everyone agrees with the performance requirements of the project
4. Completion Criteria: All performance requirements of the project are established
5. Allocated Time: 8/30/2023 - 9/16/2023
6. Owner: Jin Yuan
7. Priority: Low

**Comment by UncleHengz** [comment]
### Issue Comment
- Lay out performance requirements of the project
- To be done in the document inside team's google drive
- This lightly affects the project completion deadline as this is not the top priority out of all requirements
- There will be changes as this is currently still in progress and the team is slightly behind the set timeline
- 8/31/2023 - 9/14/2023

**Comment by jinyuan98** [comment]
### Issue Comment
- All performance requirements have been laid out
- It has been filled up inside the M1 report inside the team's google drive
- This lightly affects the project timeline as it is part of the M1 submission and this does not fully affect the functionality of the product
- There will be no changes as it has been completed
- 9/18/2023 - 9/19/2023. There were delays due to the team being slight unsure where to categorize certain non-functional requirements and also the other workloads from other modules
