### ISSUE TITLE
1.2.3.4.2 Safety Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#52]
### Issue Description
1. Task Title: 20
2. Task: To lay out the safety requirements of the project
3. Goals: Safety Requirements of the project created and agreed by everyone
4. Completion Criteria: All safety requirements of the project are established
5. Allocated Time: 8/30/2023 - 9/16/2023
6. Owner: Jia Jin
7. Priority: Low

**Comment by UncleHengz** [comment]
### Issue Comment
- Lay out safety requirements of the project
- To be done in the document inside team's google drive
- This lightly affects the project completion deadline as this is not the top priority out of all requirements
- There will be changes as this is currently still in progress and the team is slightly behind the set timeline
- 8/31/2023 - 9/14/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Safety Requirements such as making sure sensitive information are not leaked have been laid out for the project
- All safety requirements for the project are inputted inside the M1 report inside the team's google drive
- This lightly affects the project completion timeline as it is a requirement for submission, but it is not the top priority out of all tasks
- There will be no more changes as it has been completed and vetted by the team
- 9/19/2023 - 9/19/2023. There has been delays due to the team's workload affecting the timeline.
