### ISSUE TITLE
4.5 Web Server Setup

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#86]
### Issue Description 
1. Task ID: 74
2. Task: To set up the web server for product deployment
      
      - [x] #87 
      - [x] #88
      
3. Goals: Setup Web Server smoothly to allow for a smooth product deployment
4. Completion Criteria: Set up web server
5. Allocated Time: 11/20/2023 - 11/21/2023
6. Owner: Everyone
7. Priority: Medium

**Comment by cheryl-tc** [comment]
### Issue Comment
- Web Server has been setup and has been integrated together
- All information and codes have been uploaded to the team's github and google drive
- This moderately affects the project timeline due to this being a requirement for the product deployment
- No more changes will be made
- 11/21/2023 - 11/21/2023
