### ISSUE TITLE
4.5.2 Database Setup

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#88]
### Issue Description 
1. Task ID: 75
2. Task: To set up staff database and link web server to an external student database also
3. Goals: Databases setup and linked smoothly to allow for a smooth product deployment
4. Completion Criteria: Database set up and inform the team
5. Allocated Time: 11/20/2023 - 11/21/2023
6. Owner: Jin Yuan
7. Priority: Medium

**Comment by jinyuan98** [comment]
### Issue Comment
- Staff database has been setup and student database has been obtained & linked
- All codes and credentials has been shared inside team's google drive
- This moderately affects the project timeline due to this being a requirement for the product deployment
- No more changes will be made
- 11/21/2023 - 11/21/2023
